### ISSUE TITLE
For iOS do we need to add associated domain capability?

### ISSUE THREAD

**Issue by chunsfire** [flutter-institute/webauthn#22]
In order to implement webauthn passkey registration or authentication flow, iOS mandates to have associated domain capability added. This is due to underlying ASAuthorization framework.

So does this package also needs associated domain capability enabled & added in the project?

**Comment by killermonk** [comment]
This package implements its own Authenticator and is not (currently) integrating directly with the iOS or Android system-level webauthn libraries.

In other words: No, you won't need that because we don't use the system libraries.
