### ISSUE TITLE
Where do I get clientDataJSON and attestationObject from?

### ISSUE THREAD

**Issue by atresnjo** [flutter-institute/webauthn#7]
Trying to implement the webauthn flow using [FusionAuth ](https://fusionauth.io/docs/v1/tech/apis/webauthn#start-a-webauthn-passkey-assertion-or-authentication) and for the step to complete the passkey registration, the endpoint asks for a property called clientDataJSON and attestationObject. 

From my understanding, I have to create attestationObject by myself by converting the CBOR to base64 URL encoded string.
And for clientDataJSON I have to convert some parts of the first response also to base64 URL encoded string, is that correct?

 Been playing around but FusionAuth is complaining, so just want to see if I am on the right path, thanks! 👍

**Comment by killermonk** [comment]
This library was designed to sit one step behind the Javascript API for the webauthn flow, if that makes sense. Take a look at the [first image](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/webauthn-authentication-flow-01.svg?sanitize=true) on the [Yubico Developers Guide](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/WebAuthn_Client_Authentication.html). This function as the "authenticator" in that flow, so by the time this library receives the information the clientDataJSON has been hashed and is received as the clientDataHash. We then use that binary data when we create assertions and attestations.

To address your specific point, though, yes you will need to create the clientDataJSON using some data received from the request. You can find the definition of this data in the W3C standard: https://www.w3.org/TR/webauthn/#client-data . The only part you will need to grab from the Relying Party's request is the `challenge`.

Once you've created that data, you can hash it (SHA-256) and pass it to this libraries Authenticator.makeCredential method. This method will then return the attestationObject that you can use in your response. You can use the `asCBOR` method to get the binary data for the info.

Right now this library only supports the self attestation of credentials.

**Comment by killermonk** [comment]
Here's some typescript code I wrote that handles the clientDataJSON creation:
```
function getClientDataJson(type: string, options?: PublicKeyCredentialRequestOptions): Uint8Array {
    const challenge = options?.challenge as ArrayBuffer;
    const json = JSON.stringify({
        type,
        challenge: base64url(Buffer.from(challenge)),
        origin: origin,
        crossOrigin: false,
    });
    return new TextEncoder().encode(json);
}
```

It was used like this when creating the response object (the buffer was base64 encoded):
```
getClientDataJson("webauthn.get", publicKeyOptions).buffer
```

One thing I remember running in to was that the `challenge` in the JSON needed to be base64 encoded, then that JSON data was base64 encoded as well.
